<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__qty_jadi</name>
   <tag></tag>
   <elementGuidId>6bdb0b33-7507-4fc5-b0ef-e8123b2c9b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qty_jadi&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='qty_jadi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;QTY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8d9bcec-4067-412e-8e74-f1209763f246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9902a52-dd45-4f32-b202-04f4a3992162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty_jadi</value>
      <webElementGuid>01cf1372-f5c7-4a77-baf7-eba77d0b30ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control center</value>
      <webElementGuid>ee39ff7f-f7c5-4954-bac3-5db545e28d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>QTY</value>
      <webElementGuid>de547a9e-4253-422f-b3cf-ad46ad2d3d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return numbersonly(this, event);</value>
      <webElementGuid>f3485802-e417-4b24-a766-87a03648c70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:tandaPemisahTitik(this);</value>
      <webElementGuid>085b3b21-ba4c-4241-ab97-af163bb17473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal form-bordered&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/input[@class=&quot;form-control center&quot;]</value>
      <webElementGuid>a918579d-f6d2-4330-a5a3-b6108e5f9edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qty_jadi']</value>
      <webElementGuid>bd35a8a6-1d3b-41b2-8b2b-768478465375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-1']/div/form/div/div[2]/input</value>
      <webElementGuid>fb892e71-ccb8-4fe3-9185-6946fdfe7798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2d38b761-a4d3-4cd5-ad3f-c34785b9c8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'qty_jadi' and @placeholder = 'QTY']</value>
      <webElementGuid>3f7c0446-af36-43a8-9f4f-d21c0906c0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
