<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__barcode</name>
   <tag></tag>
   <elementGuidId>a05e1632-1a0d-4033-ac47-86f3ef020d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;barcode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='barcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Input Barcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52c403f5-7049-4a31-bba1-bdcf6a0c5519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>814ebdba-c2a2-4d5e-b7f1-8b23bf476afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>barcode</value>
      <webElementGuid>db7fd738-f562-4b1e-9333-ebc7b803a699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control center</value>
      <webElementGuid>f8adf0da-954e-4b68-bd77-221e0937cf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Barcode</value>
      <webElementGuid>0aefdc2d-31dc-45a1-b523-053c9fce42ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase()</value>
      <webElementGuid>23128cb7-b869-4f45-8875-3f24578aba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal form-bordered&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-3&quot;]/input[@class=&quot;form-control center&quot;]</value>
      <webElementGuid>18223833-b81f-4f84-8fdb-a117f3fa1833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='barcode']</value>
      <webElementGuid>44664866-53e1-42b6-ba1e-74a6de606f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-1']/div/form/div/div/input</value>
      <webElementGuid>ecf4f5ab-b28a-414e-a9c3-cbb821506b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8b967247-c1cd-4cce-9194-78cab428a222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'barcode' and @placeholder = 'Input Barcode']</value>
      <webElementGuid>09eea20e-10ff-4978-b7ec-c8c828acecef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
