<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>646dac1c-8309-430b-b8b3-e5a5a42e7a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.dropdown-toggle.center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='panel-1']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cb29259-5b73-4cde-b4f6-f55457d21487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/alkes/c_steril/produk_steril_ok</value>
      <webElementGuid>881f8466-9172-4efe-bba8-08ba9caec63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary dropdown-toggle center</value>
      <webElementGuid>dc4f627e-8add-4850-9fe4-f7288f7eae75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										 Save
									</value>
      <webElementGuid>23526a0d-58fd-4e4a-9efe-03abb78f4c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1&quot;)/div[@class=&quot;panel-body&quot;]/a[@class=&quot;btn btn-primary dropdown-toggle center&quot;]</value>
      <webElementGuid>4caa9bd8-5d0d-47c1-aefb-30671fbba73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-1']/div[2]/a</value>
      <webElementGuid>3527b4ef-cbb0-446c-b29a-92c3ea07cbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>4eebcd26-2e78-44de-9493-fd7ef3dbd447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/following::a[1]</value>
      <webElementGuid>67c2b474-67ce-4f91-bac7-c55fdb9d4077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GEL&amp;CLOT ACTIVATOR 3 ML'])[1]/following::a[3]</value>
      <webElementGuid>5711ec5d-0ecd-4fad-be50-201dba8e8fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>cccba847-d35e-43ad-b5f7-d028e8f1f585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/alkes/c_steril/produk_steril_ok']</value>
      <webElementGuid>30cd900e-3344-4bc2-b343-40d977a76ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>bc8c5120-613d-4db7-95ce-af7cb23fbcda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/alkes/c_steril/produk_steril_ok' and (text() = '
										 Save
									' or . = '
										 Save
									')]</value>
      <webElementGuid>187c5c28-af09-4343-908f-32f54b203014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
