<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__qty_steril</name>
   <tag></tag>
   <elementGuidId>be56a92b-a32f-4adb-93f7-cf2e3dd4435c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qty_steril&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='qty_steril']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;QTY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a25dece-4db7-4008-bcfc-4a1f9bbb0c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>27fdadeb-aa8a-4c9b-823a-0ae33ad13856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc7adb30-6dda-4414-9285-600cf17c73c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty_steril</value>
      <webElementGuid>7e2cf81e-9e77-4e70-98aa-97eb8a6cf9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control center</value>
      <webElementGuid>6393b3c3-5357-4230-a999-300c99a22760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>QTY</value>
      <webElementGuid>c27736cb-4c75-4a91-93f6-f1da77ffce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal form-bordered&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/input[@class=&quot;form-control center&quot;]</value>
      <webElementGuid>aa2c7d10-7a26-4b1d-832c-c4217f6173c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qty_steril']</value>
      <webElementGuid>9e113f09-d62a-425f-aa14-f878a8cb2783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panel-1']/div/form/div/div[2]/input</value>
      <webElementGuid>9e53cbaf-2665-48c2-aabe-0e1fad3bbc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>27981f64-9880-4664-bcc9-6a6c5f5b7e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'qty_steril' and @placeholder = 'QTY']</value>
      <webElementGuid>be9f6f5c-8bac-40b9-b6a7-45c2c12d6c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
